#!/bin/sh

# ovfdep - VMware OVF deployment helper
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#

case "$1" in
    startup)
	if [ X`getent shadow root|cut -d: -f1-2|grep ':$'|cut -d: -f1` = 'Xroot' ]; then
	    while ! passwd root; do echo; echo 'ROOT PASSWORD IS REQUIRED!'; echo; done
	fi
	;;
    cleanup)
	passwd -d root
	;;
esac
