#!/bin/sh

# ovfdep - VMware OVF deployment helper
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#

case "$1" in
    startup)
	if [ -n $(shopt -s nullglob; echo /etc/ssh/ssh_host_*) ]; then
	    dpkg-reconfigure openssh-server
	fi
	;;
    cleanup)
	if [ -n $(shopt -s nullglob; echo /etc/ssh/ssh_host_*) ]; then
	    echo "Removing openssh-server's host keys..."
	    rm -vf /etc/ssh/ssh_host_*
	fi
	;;
esac
