#!/bin/sh

# ovfdep - VMware OVF deployment helper
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#

case "$1" in
    startup)
	;;
    cleanup)
	echo "Clean up home dirs..."
	getent passwd | cut -d: -f6 | getent passwd |cut -d: -f6 | egrep -v '^/(dev|tmp|proc|sys|bin|usr|var/run|run|$)' |
	while read home; do
	    rm -vf \
		"$home/.bash_history"				# bash
		"$home/.lesshst"				# less
		"$home/.mc/history"				# mc
		"$home/.mc/cedit/cooledit.clip"			# mc
		"$home/.local/share/mc/filepos"			# mc
		"$home/.local/share/mc/history"			# mc
		"$home/.local/share/mc/mcedit/mcedit.clip"	# mc
		"$home/.mysql_history"				# mysql-client
		"$home/.psql_history"				# postgresql-client
	    rm -vfr "$home/.cache";
	done
	;;
esac
