#!/bin/sh

# ovfdep - VMware OVF deployment helper
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#

NTP_CONF='/etc/ntp.conf'
NTP_OVFDEP_CONF='/var/lib/ntp/ntp.conf.dhcp'

OVFDEP_NTP="$OVFDEP_XSLDIR/ntp.xsl"

case "$1" in
    startup)
        ntpservers=`xsltproc "$OVFDEP_NTP" "$OVFDEP_OVFENV"`
	if [ -n "$ntpservers" ]; then
	    echo "Configuring ntp..."

	    tmp=$(mktemp "$NTP_OVFDEP_CONF.XXXXXX") || return
	    chmod --reference=$NTP_CONF $tmp
	    chown --reference=$NTP_CONF $tmp

	    (
		echo "# This file was copied from $NTP_CONF with the server options changed"
		echo "# to reflect the information configured by the OVF environment.  Any changes made"
		echo "# here will be lost at the next reconfiguration.  Edit $NTP_CONF instead."
		echo
		echo "# NTP server entries configured by the OVF environment:"
		echo $ntpservers
		sed -r -e '/^ *(server|peer).*$/d' $NTP_CONF
	    ) >> $tmp
	
	    mv $tmp $NTP_OVFDEP_CONF
	fi
	;;
    cleanup)
	echo "Clean up ntp.drift..."
	rm -vf /var/lib/ntp/ntp.drift
	;;
esac
